language: java
script: "mvn clean deploy --settings maven-settings.xml"
sudo: required
jdk:
  - oraclejdk8
  
branches:
  only:
  - master
  - 1.0.x
  
env:
  global:
  - secure: D2HZn2fTJ0wm0bgQsBVWi3mOSm7w6ARGzeK2ILNdw0Nq5CsDNFDN72sSYJ0Tt+9wi2h/GxsWe2EC2N/LqRA3w7dUgphbPVJ6pEZNginz3Udst9kUuxBXsZDVLihAsMTM5ySanao+rqYh/ezjcVVucbybpUUJDGaXHfH3I4Yc6uR3OTS7d6VsY+w8xgm6/tc4Eku81zFeXoyB4evmeg3SkzDyaA86iFPor+6SBilST+h+aGyTOj/b3NNIxiu1E20EmpD+vBkpPmcQkzL3pjM4+Mf+hG1pF3rbeO9WCu3DAFcy7gfk39+bGy0OZba1G8Yp70+ZJqtBEt3tX6vLw+YcMcTv5B9HZr0qyXsPdN5qeVaQZiPuJpMeMa1oXoO1lGVyZkIjF0Pj0vPece2aZKVh1DaF/EEaDgDMetfB7b1TXWUIiHG59IJJGEsisP1qFK/igMHJHce1khIfEo7prWWz0ghE9sqS91accOEemVxd+JLnd7R3LdTXRE7urpFvxUyivg6EfYCl/QkOQ/cUsz87OVNENd2fxkSxiswCk209eQMoOPAbyxId9D4yPYz8pqk211ZLkd+cpZP77hGTgg6qtfogJb6eCbD/oQwptVFGaxxdR0GXSqjEhir/68Qec9crg9WCnTGu6u4RkuIxcECzE0dO4wewdRsXZzD2USteKHg=
  - secure: TZAsntfOTJip9qb6+OEGiLkqD67MEqQGWCDmKgFl87IQHfr1WbRsqhITLO2BpMyk5s4iooSfnrixhlUWdrpY2cBPyDd8ZPwP7KcsatAj5E1LPIdpf6x45jWYCrM8Ylhpn8DztBvJgcQjwjkvJJzKffI2Q4E/A88WQjzMDkSJArz5Ghp9o8W6Q+o+AUldh2TvV/ntYDjFL0zbpBVAu0tlpIlNmtfZ4Lb2hgQnkVsivOaiX6oBKIATGgAFbGWxSJp88jsENAKNQKogy2aRkrdiQD2vwVGfyCexUNJ8GJcDpcoLw/MQkTbZZ5oB5EUyqKSy7vFPdJZsF6uYVA+/R2+TDzyCMI2JoT3kS8N8Z1PcRKsrFFAjxGWTFW3J6p1uUeZAAI9ODmwpYhvnVkpEv98SUA7LSx46Gbs+DqVGFQJKEjyXRXD2risxTiPpKMx9aOoiCFAMka2o8X8ZYSO8NPc//jgrBDAqLFtK7OYBIAbA5ltQPyZryEmWAhEuYs96wBpuU2yABkcnp9FD5n9CjKtghfWbGzTZkqnSGamjzSaL1xtTACYPs8Zx/EdMn9k1cRwtYORsZOGTzaJ9PMEUHfiqbvQzq9rr1+HYxE4gW3js3DhgH2FCs9eviuzq7sI8HhZN4ig3B5suJtr6o393TptnrDgVKGzyEbBqkOy9fNuEu94=
